[package]
name = "watt"
version = "0.1.0"
authors = ["Nicolas Winkler <nicolas.winkler@gmx.ch>"]
edition = "2018"

[toolchain]
targets = ["aarch64-unknown-linux-gnu"]

[dependencies]

[build-dependencies]
bindgen = "*"
